### ISSUE TITLE
Mouse focus only happens after motion

### ISSUE THREAD

**Issue by yorickvP** [emersion/slurp#26] opened 2019-02-12 20:46 UTC
If you start slurp, then, without moving, click the mouse, then move the mouse, slurp doesn't know that the button is pressed already. This results in selections with no UI that start on 0,0.

**Comment by emersion** [comment] 2019-02-12 21:13
Duplicate of https://github.com/swaywm/sway/issues/3080

This is a sway bug, so I'll close this.

**Closed by emersion** 2019-02-12 21:13 UTC
