### ISSUE TITLE
Focus stolen from XWayland applications

### ISSUE THREAD

**Issue by zikaeroh** [emersion/slurp#47] opened 2020-01-18 00:38 UTC
I often need to screenshot tooltips in VS Code. When I do something like:

```sh
sleep 5; grim -g "$(slurp)" - | wl-copy
```

To paste somewhere to report a bug, `slurp` appears to be stealing focus away from the window, which makes the tooltip disappear (thus meaning grim screenshots after what I wanted to screenshot is gone).

This appears to happen only for XWayland clients, so in my case Chromium-based applications like VS Code, Chromium itself, etc. If I repeat this for the right-click menu of my terminal (which is VTE -> GTK -> Wayland directly), then I can properly select and screenshot the tooltip.

Is this inherent to the way XWayland applications detect focus, or would it be possible to prevent `slurp` from "stealing" focus away?

My workaround has been to not use `slurp`, and go edit my screenshot later, as `grim` itself doesn't "steal" focus.

**Comment by emersion** [comment] 2020-01-18 00:52
Duplicate of https://github.com/emersion/slurp/issues/43

**Closed by emersion** 2020-01-18 00:52 UTC

**Comment by zikaeroh** [comment] 2020-01-18 00:53
My bad, I had really thought I had searched.
