### ISSUE TITLE
Broken selection across multiple outputs with latest release

### ISSUE THREAD

**Issue by shumvgolove** [emersion/slurp#78] opened 2020-11-17 00:45 UTC
- Slurp 1.3.1
- Sway 1.5.1

Running `slurp` and selecting region across multiple outputs results in this:
```
selection cancelled
```

**Comment by emersion** [comment] 2020-11-17 07:43
Duplicate of https://github.com/emersion/slurp/issues/72

**Closed by emersion** 2020-11-17 07:43 UTC

**Comment by shumvgolove** [comment] 2020-11-17 11:32
Oh, sorry, didn't notice.
